# Generated by Django 5.0 on 2026-01-23 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('salary_range', models.CharField(blank=True, help_text='e.g., KES 50,000 - 100,000', max_length=100)),
                ('job_outlook', models.TextField(blank=True, help_text='Career prospects in Kenya')),
                ('required_qualifications', models.TextField(help_text='Educational requirements')),
                ('skills_needed', models.TextField(blank=True)),
                ('related_courses', models.TextField(blank=True, help_text='University/college courses')),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'KUCCPS Cluster',
                'verbose_name_plural': 'KUCCPS Clusters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Education Level',
                'verbose_name_plural': 'Education Levels',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareerPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_success_rate', models.DecimalField(decimal_places=2, help_text='Percentage likelihood', max_digits=5)),
                ('gap_analysis', models.JSONField(help_text='Subjects needing improvement with targets')),
                ('recommended_resources', models.JSONField(blank=True, default=list)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiguide.career')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_predictions', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Career Prediction',
                'verbose_name_plural': 'Career Predictions',
                'ordering': ['-prediction_date', '-predicted_success_rate'],
            },
        ),
        migrations.AddField(
            model_name='career',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers', to='digiguide.cluster'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('age_range', models.CharField(blank=True, help_text='e.g., 6-7 years', max_length=50)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='digiguide.educationlevel')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['education_level__order', 'order'],
                'unique_together': {('education_level', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_core', models.BooleanField(default=False, help_text='Core/compulsory subject')),
                ('education_levels', models.ManyToManyField(related_name='subjects', to='digiguide.educationlevel')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClusterSubjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_grade', models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E', 'E')], max_length=2)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiguide.cluster')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiguide.subject')),
            ],
            options={
                'verbose_name': 'Cluster Subject Requirement',
                'verbose_name_plural': 'Cluster Subject Requirements',
                'unique_together': {('cluster', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='cluster',
            name='required_subjects',
            field=models.ManyToManyField(related_name='clusters', through='digiguide.ClusterSubjectRequirement', to='digiguide.subject'),
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Academic year')),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('score', models.DecimalField(decimal_places=2, help_text='Percentage score', max_digits=5)),
                ('grade', models.CharField(choices=[('A', 'A (80-100)'), ('A-', 'A- (75-79)'), ('B+', 'B+ (70-74)'), ('B', 'B (65-69)'), ('B-', 'B- (60-64)'), ('C+', 'C+ (55-59)'), ('C', 'C (50-54)'), ('C-', 'C- (45-49)'), ('D+', 'D+ (40-44)'), ('D', 'D (35-39)'), ('D-', 'D- (30-34)'), ('E', 'E (0-29)')], max_length=2)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='accounts.studentprofile')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiguide.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiguide.subject')),
            ],
            options={
                'verbose_name': 'Academic Record',
                'verbose_name_plural': 'Academic Records',
                'ordering': ['-year', '-term', 'subject'],
                'unique_together': {('student', 'subject', 'grade_level', 'year', 'term')},
            },
        ),
    ]
